// Automatically generated from global.css. Do not edit directly.
export const Colors = {
    dark: {
        white: "#fff",
        black: "#000",
        lime: "#7ccf00",
        amber: "#ffba00",
        pink: "#f6339a",
        purple: "#ad46ff",
        colorShadowNb: "#fff",
        background: "#0a0a0a",
        foreground: "#fafafa",
        card: "#171717",
        cardForeground: "#fafafa",
        popover: "#171717",
        popoverForeground: "#fafafa",
        primary: "#1d4ed8",
        primaryForeground: "#171717",
        secondary: "#262626",
        secondaryForeground: "#fafafa",
        muted: "#262626",
        mutedForeground: "#a1a1a1",
        accent: "#262626",
        accentForeground: "#fafafa",
        destructive: "#ff6467",
        destructiveForeground: "#fff",
        ring: "#737373",
        border: "rgba(255, 255, 255, 0.1)",
        input: "rgba(255, 255, 255, 0.15)",
    },
    light: {
        white: "#fff",
        black: "#000",
        lime: "#9ae600",
        amber: "#ffd230",
        pink: "#fb64b6",
        purple: "#c27aff",
        colorShadowNb: "#000",
        background: "#fff",
        foreground: "#0a0a0a",
        card: "#fff",
        cardForeground: "#0a0a0a",
        popover: "#fff",
        popoverForeground: "#0a0a0a",
        primary: "#1d4ed8",
        primaryForeground: "#fafafa",
        secondary: "#f5f5f5",
        secondaryForeground: "#171717",
        muted: "#f5f5f5",
        mutedForeground: "#737373",
        accent: "#f5f5f5",
        accentForeground: "#171717",
        destructive: "#e7000b",
        destructiveForeground: "#fff",
        ring: "#a1a1a1",
        border: "#e5e5e5",
        input: "#e5e5e5",
    },
} as const;
